### ISSUE TITLE
widgets are not showing on ds cl4 lite mobile 

### ISSUE THREAD

**Issue by abrar0123** [sAleksovski/react-native-android-widget#101]
I am trying to pick the widgets from the widget picker, but when I tested it on the DS CL4 Lite mobile, it did not display. However, on other brands like Samsung, Vivo, Infinix, etc., it successfully displayed.
@SAleksovski, could you please share your thoughts on the issue and how we can resolve it so the widgets display correctly?

**Comment by sAleksovski** [comment]
What didn't display? The widget in the picker, or the widget when dropped on homescreen?

What is DS CL4 Lite, I couldn't find it googling.

As with previous issue, please provide more information, like:
- Android version
- relevant logs
- reproducible example
