### ISSUE TITLE
The widgetTaskHandler function cannot be triggered.

### ISSUE THREAD

**Issue by anno-er** [sAleksovski/react-native-android-widget#103]
Hello~!
I built a Hello-Widget project following the tutorial on the official website. The widget can be dragged to the desktop screen. However, the rendered content only has a white border. And I printed it in the registered widgetTaskHandler function, but it was not triggered. Is there anything I did wrong?

react native 0.72.0
Api35 x86_64

![Snipaste_2024-11-07_00-38-57](https://github.com/user-attachments/assets/03f1139b-4e3e-4974-bf37-33e87d518f5d)

**Comment by sAleksovski** [comment]
Hi, 

You probably missed a step. Did you [register the task handler] (https://saleksovski.github.io/react-native-android-widget/docs/tutorial/register-task-handler#register-widget-task-handler)?

If you did, then please share the repo and I can take a look.

**Comment by anno-er** [comment]
> Hi,
> 
> You probably missed a step. Did you [register the task handler] (https://saleksovski.github.io/react-native-android-widget/docs/tutorial/register-task-handler#register-widget-task-handler)?
> 
> If you did, then please share the repo and I can take a look.

Hello!

I've found out why. In the widget/xx.java file, I set the wrong project name, causing the event to not be distributed correctly. Thank you very much for your help.
![Snipaste_2024-11-07_23-02-38](https://github.com/user-attachments/assets/4f5a2fae-fc6b-44d3-9452-c3b46db1dc74)
