### ISSUE TITLE
'AndroidWidget' could not be found.

### ISSUE THREAD

**Issue by rocketmay** [sAleksovski/react-native-android-widget#107]
I have a fresh expo go project, with a fresh install of react-native-android-widget in Windows. When I run `npx expo start` and use Expo Go to run the app on my phone, I receive the following error:

```
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'AndroidWidget' could not be found. Verify that a module by this name is registered in the native binary.
```

I've also tried loading in the repo and running the example in the example-expo folder but still see the same error. Any ideas? 

```
"dependencies": {
    "@react-native-async-storage/async-storage": "^2.0.0",
    "@react-navigation/native": "^6.1.14",
    "@react-navigation/native-stack": "^6.9.22",
    "expo": "^52.0.11",
    "expo-dev-client": "~5.0.4",
    "expo-splash-screen": "^0.29.13",
    "react": "18.3.1",
    "react-native": "0.76.3",
    "react-native-android-widget": "^0.15.1",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "^3.34.0"
  },
```

**Comment by sAleksovski** [comment]
This library cannot be used with Expo Go, you need to create a dev client. 

https://saleksovski.github.io/react-native-android-widget/docs/tutorial/try-it-our

https://docs.expo.dev/versions/latest/sdk/dev-client/
