### ISSUE TITLE
Click action issue in Redmi devices

### ISSUE THREAD

**Issue by shvdev20** [sAleksovski/react-native-android-widget#108]
Dear react-native-android-widget Maintainers,

I’m encountering an issue where click actions on widgets built with your library do not work on certain Redmi devices. The same widget functions correctly on other Android devices, so it appears to be device-specific.

This might be related to MIUI’s handling of widget interactions. I would appreciate any guidance or potential workarounds.

I am using the "react-native-android-widget": "^0.14.0"

Thank you for your support!

**Comment by sAleksovski** [comment]
Can you specify which Redmi devices, and what Android version they are running?

Can you share some logs?

**Comment by shvdev20** [comment]
Xiaomi Redmi Note 8 pro and some other Xiaomi phones that users have reported. There is no log. Just Click Action don't work and nothing happen.

**Comment by sAleksovski** [comment]
**what Android version they are running?**

Without access to logs I cannot help you, I don't have a Redmi phone.

**Comment by sAleksovski** [comment]
Closing this since I don't have enough information to do anything about it.
Feel free to reopen with more information.
