### ISSUE TITLE
Demo isn't working

### ISSUE THREAD

**Issue by avmutius** [sAleksovski/react-native-android-widget#109]
Hey man, that's me right now:
![image](https://github.com/user-attachments/assets/a5aca2d7-1b0e-406f-89a0-a68ca58710d1)

I was spending 2 days figuring out why the widget is not working, even copying your whole demo expo project. 
Now i saw that you wrote in your recent version that new gen isn't supported, however its enabled in your demo project.
Please fix it to save lives.

**Comment by sAleksovski** [comment]
Sorry it wasn't more clear.
I set `newArchEnabled` to false in the expo demo, and opened #110 to track the crash on new arch.
