### ISSUE TITLE
Missing tsconfig import

### ISSUE THREAD

**Issue by bo-carey** [sAleksovski/react-native-android-widget#11]
Upon initially pulling and running `yarn install`, I ran into an issue where `@tsconfig/react-native/tsconfig.json` was not found. I was able to fix it by running `yarn add @tsconfig/react-native`. 

Let me know if this is something specific to me so I can see what I might have done wrong.

Thanks!

**Comment by sAleksovski** [comment]
I missed this when I migrated to the latest React Native version.

It should be fixed now.
