### ISSUE TITLE
Question: how can I fetch the data on widget click?

### ISSUE THREAD

**Issue by nad182** [sAleksovski/react-native-android-widget#15]
> This might be a limitation of this library, but I feel like there should be a way to do what I need. I realize this is a question, not an issue with the library, but I couldn't find a better way to ask for help.

**Prerequisites:**
1. I have a working widget created with this lib on an Android device.
2. There is a button in the widget the should trigger an API request and update the UI with the returned data.

**Things I've tried:**
1. Set `clickAction` as in the code below:
```js
<IconWidget
  font="material"
  icon="refresh"
  clickAction="REFRESH_WIDGET"
/>
```
2. Add a case in `widget-task-handler.js` to handle that `clickAction`:
```js
case 'WIDGET_CLICK':
  if (widgetInfo.widgetName === 'CustomWidget') {
    if (props.clickAction === 'REFRESH_WIDGET') {
      const cards = await AsyncStorage.getItem('cards');
      const parsedCards = cards ? JSON.parse(cards) : [];

      const listNames = await AsyncStorage.getItem('listNames');
      const parsedListNames = cards ? JSON.parse(listNames) : {};

      props.renderWidget(
        <CustomWidget
          cards={parsedCards}
          listNames={parsedListNames}
        />,
     );
    }
  }
  break;
```
But obviously that just returns the existing data from `AsyncStorage`.

3. Add/update `AsyncStorage` entry in the case statement above and listen for it in the components `useEffect` hook. Though I'm not sure what my `useEffect` should look like, since `AsyncStorage` is asynchronous and it needs to execute every time the `shouldFetch` value is updated in `AsyncStorage`:
```js
case 'WIDGET_CLICK':
  if (widgetInfo.widgetName === 'CustomWidget') {
    if (props.clickAction === 'REFRESH_WIDGET') {
      await AsyncStorage.setItem('shouldFetch', 'true');
      // ...
```

**Comment by sAleksovski** [comment]
You are mostly there with the code you shared.

1. This is OK, you are setting a `clickAction` that you can handle in the `widget-task-handler`
2. This is *mostly* OK.

I'm not sure why you are reading the data from `AsyncStorage`. When did you put it there?
The data for the widget does not need to be in `AsyncStorage`. Technically, you don't even need to store it anywhere, you just need to pass it to the widget when you render it.

You can do the API request here, and pass the data to the widget.
The widget should receive all the data it needs from props. Look at it as a pure function/component that receives some data/props, and returns the JSX for the widget.

Here is an example:

```js
case 'WIDGET_CLICK':
  if (widgetInfo.widgetName === 'CustomWidget') {
    if (props.clickAction === 'REFRESH_WIDGET') {
      const data = await fetch('https://example.com/api').then((response) => response.json());

      const cards = data.cards;
      const listNames = data.listNames;

      props.renderWidget(
        <CustomWidget
          cards={cards}
          listNames={listNames}
        />,
     );
    }
  }
  break;
```

3. I'm not sure I understand this part, but making the API request in 2. should cover your use-case

**Comment by nad182** [comment]
Oh I see, thank you! I was under the impression that I cannot make API calls or get necessary external data (e.g. component local state) data inside `widget-task-handler.js` or "widget" files, where I'm using primitives. But what you're suggesting makes sense. I will try it out!

**Comment by sAleksovski** [comment]
Yes, you cannot use hooks, API calls, or anything async inside the widget component.

widget-task-handler is a regular file, and you can do anything in it.

**Comment by nad182** [comment]
Thanks again for your help! I created the PR to add this information to the docs. Feel free to edit, accept or close it.
