### ISSUE TITLE
Widget requires a click for Widget Task Handler to be triggered.

### ISSUE THREAD

**Issue by mark-yacoub** [sAleksovski/react-native-android-widget#18]
hello

When I add add or resize a widget, it shows a gray overlay with text "Click to update widget"
<img width="351" alt="image" src="https://github.com/sAleksovski/react-native-android-widget/assets/11547193/72394fee-d072-4fcd-bcb2-f491615bad71">

only after i click that `widgetTaskHandler` gets called.

**Comment by sAleksovski** [comment]
This is a limitation of the library and the way how the native code communicates with React Native.

It is mentioned in the docs  https://saleksovski.github.io/react-native-android-widget/docs/limitations

**Comment by mark-yacoub** [comment]
Thanks for the info
is this a technical limitation or it might be solved in a future release?

**Comment by sAleksovski** [comment]
As far as I understand it, this is a technical limitation for Android 12+.
There might be some solution, but I was not able to find it.

I'll close this issue, since this is documented in the documentation.
If someone has an idea about a potential fix, feel free to contact me.

**Comment by sAleksovski** [comment]
I just released version `0.6.0` that addresses this issue, along with several other features.

See the details at the [release page](https://github.com/sAleksovski/react-native-android-widget/releases/tag/v0.6.0)

**Comment by mark-yacoub** [comment]
thanks for the release page, it helped me upgrade very smoothly.
I tried the new version and it's working great!
