### ISSUE TITLE
click invalid and  show wrong

### ISSUE THREAD

**Issue by 13627491210** [sAleksovski/react-native-android-widget#19]
hello， please look at this picture.  phone is Meizu，but other phone is OK。 can't click and seem as  width is error。

![CB976FEC862FDFF4963FB6AEFC60E6E5](https://github.com/sAleksovski/react-native-android-widget/assets/37203543/7ae17b77-86d9-420e-a275-b88ae058859d)

**Comment by sAleksovski** [comment]
Hi

Can you tell me what Launcher is Meizu using?
I don't have a Meizu phone, so I'm not sure how I can reproduce it, but I'll try in the following days.

**Comment by 13627491210** [comment]
> Hi
> 
> Can you tell me what Launcher is Meizu using? I don't have a Meizu phone, so I'm not sure how I can reproduce it, but I'll try in the following days.

Hi

**Comment by 13627491210** [comment]
> Hi
> 
> Can you tell me what Launcher is Meizu using? I don't have a Meizu phone, so I'm not sure how I can reproduce it, but I'll try in the following days.

Hi， I think it  is system Launcher,   maybe Flyme os ?

**Comment by sAleksovski** [comment]
I just released `0.6.1`, trying to resolve some of these issues.
Now the widget might be cropped on some launchers that do not report the correct widget size, but touch will work correctly.

Can you try it to see if it fixes your issue?

**Comment by 13627491210** [comment]
> I just released `0.6.1`, trying to resolve some of these issues. Now the widget might be cropped on some launchers that do not report the correct widget size, but touch will work correctly.
> 
> Can you try it to see if it fixes your issue?

Hi, I updated  0.6.1 ， but i got a question 。 can you help me ?
<img width="892" alt="image" src="https://github.com/sAleksovski/react-native-android-widget/assets/37203543/6ddb4afe-9762-4070-be69-e02782c9fd76">

**Comment by 13627491210** [comment]
> > I just released `0.6.1`, trying to resolve some of these issues. Now the widget might be cropped on some launchers that do not report the correct widget size, but touch will work correctly.
> > Can you try it to see if it fixes your issue?
> 
> Hi, I updated 0.6.1 ， but i got a question 。 can you help me ? <img alt="image" width="892" src="https://user-images.githubusercontent.com/37203543/246055121-6ddb4afe-9762-4070-be69-e02782c9fd76.png">

0.5.3  is OK

**Comment by sAleksovski** [comment]
Set `compileSdkVersion` to 33 in `build.gradle`

**Comment by sAleksovski** [comment]
I'll close this issue since there was no response.
You can reopen it if the problem is still there.
