### ISSUE TITLE
Detecting if widget is installed

### ISSUE THREAD

**Issue by systemride** [sAleksovski/react-native-android-widget#28]
Hello, this library is great thank you for doing this!

I'm curious what you think about adding something that would allow the app to determine if any widgets have been installed? Perhaps a count, or even an array of widget names?

It would be nice to show in the app some kind of status indicator of which widgets have been installed.

**Comment by sAleksovski** [comment]
You can use https://saleksovski.github.io/react-native-android-widget/docs/public-api#getwidgetinfo .
For a given `widgetName` it will return a list of installed widgets.
If you have multiple widgets defined in the app you can call the `getWidgetInfo` function multiple times.

**Comment by systemride** [comment]
Got it, that's exactly what I was looking for. Thank you!
