### ISSUE TITLE
ImageWidget sometime missing when WIDGET_UPDATE trigger

### ISSUE THREAD

**Issue by nguyenduy2392** [sAleksovski/react-native-android-widget#29]
On first time added widget to screen, ImageWidget working, but when i close my app and WIDGET_UPDATE trigger so ImageWidget is not working. my source image is src/assets/images/widget2.png
    Thanks for any help!

`case 'WIDGET_UPDATE':
      props.renderWidget(
        <Widget {...widgetInfo} />
      )
      break;`
      
      `<ImageWidget
               image={require('../../assets/images/widget2.png')}
               imageWidth={imageWidth}
               imageHeight={imageHeight}
               radius={10}
      />`

**Comment by sAleksovski** [comment]
Do you get an error in the console?

Is your app running in production mode, or development mode?

If you are working in development mode, the server must be started, but I'm not sure if images will load when app is killed.

For production mode it should work.

**Comment by sAleksovski** [comment]
Reopen the issue if you still have the problem in production mode.
