### ISSUE TITLE
Excuse me, when the app is terminated, is updatePeriodMillis unable to update widgets?

### ISSUE THREAD

**Issue by A-ANing** [sAleksovski/react-native-android-widget#30]
I like this package very much. My widget is counting down days. It needs to be updated after the app ends. What should I do?

**Comment by A-ANing** [comment]
I tried it, and it seems that updatePeriodMillis can still be configured to trigger WIDGET_UPDATE update after the application process ends. Is that so

**Comment by sAleksovski** [comment]
https://saleksovski.github.io/react-native-android-widget/docs/update-widget#updateperiodmillis

The widget can be updated even when the app is in background.

You can try this with the example app from the latest release (https://github.com/sAleksovski/react-native-android-widget/releases/tag/v0.7.0) by adding the `DebugEvents` widget and waiting.
