### ISSUE TITLE
Custom Widget Configuration Screen

### ISSUE THREAD

**Issue by robrechtme** [sAleksovski/react-native-android-widget#32]
Hi! First of all, super nice lib! I have tried to implement widgets in RN before and it was a real struggle. This lib in combination with the docs makes it super easy.

One thing that is missing, which is often needed when adding widgets, is a configuration screen in which you can choose what the widget should display. See https://developer.android.com/develop/ui/views/appwidgets/configuration. Do you think there is a way to include this in the library? Or is this too tightly linked to the project to be extracted to a library? 🤔

**Comment by sAleksovski** [comment]
Hi. 
Thanks for the nice words.

A configuration screen sounds useful to have. Even thought it is specific per app, maybe I can add an option to the widget to open a deep link in the app once it is dropped on the screen, and apps that use the widget will need to handle that deep link.

The configuration activity is an Android activity, I'm not sure how I can link it to a React Native screen, but I can investigate more.

**Comment by mefjuu** [comment]
@robrechtme I came up with kinda different approach to the problem you are talking about. My widget data "model" is kept in AsyncStorage, so I can parse it in app, change it and finally render the widget with the fresh data. 
One thing I haven't done yet is placing an edit button on widget, which opens that config screen.

**Comment by sAleksovski** [comment]
That's one possible workaround.
 https://developer.android.com/develop/ui/views/appwidgets/configuration#reconfigure-widgets allowes you to reconfigure the widget without having an edit icon present at all times, only on long press on the widget.

**Comment by robrechtme** [comment]
@sAleksovski the deep link approach sounds interesting. I was playing around with opening a new activity like the docs do, but then there needs to be a way to hook that activity up to React Native. Haven’t figured that out yet.

**Comment by sAleksovski** [comment]
I just release version `0.8.0` that includes a way to make widgets configurable, using a separate configuration activity/screen.

You can see the new docs at https://saleksovski.github.io/react-native-android-widget/docs/tutorial/make-widget-configurable
