### ISSUE TITLE
widget didn't show anything

### ISSUE THREAD

**Issue by rmd1710714107** [sAleksovski/react-native-android-widget#37]
i follow this [instruction](https://saleksovski.github.io/react-native-android-widget/docs/tutorial/register-widget-expo), but the widget didn't show anything. And the `app.json` show here:
```json
"plugins": [
      [
        "react-native-android-widget",
        {
          "widgets": [
            {
              "name": "Hello",
              "label": "My Hello Widget",
              "minWidth": "320dp",
              "minHeight": "120dp",
              "description": "This is my first widget",
              "previewImage": "./assets/icon.png",
              "updatePeriodMillis": 1800000
            }
          ]
        }
      ]
    ]
```
the version of module is here:
```json
"dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-native-community/netinfo": "9.3.7",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "@reduxjs/toolkit": "^1.9.5",
    "dayjs": "^1.11.9",
     ** "expo": "~48.0.18", **
    "expo-image": "~1.0.1",
    "expo-sqlite": "~11.1.1",
   "expo-status-bar": "~1.4.4",
    "native-base": "^3.4.28",
     ** "react": "18.2.0", **
    "react-native": "0.71.8",
     ** "react-native-android-widget": "^0.7.0", ** 
    "react-native-checkbox-reanimated": "^0.1.1",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-svg": "13.4.0",
    "react-native-swipe-list-view": "^3.2.9",
    "react-redux": "^8.1.1",
    "styled-components": "^6.0.3"
  },
```
the code in widget component is same as the tutorial [Widget Design](https://saleksovski.github.io/react-native-android-widget/docs/tutorial/widget-design) and [Widget Preview](https://saleksovski.github.io/react-native-android-widget/docs/tutorial/widget-preview)

**Comment by sAleksovski** [comment]
Where didn't the widget show anything? Home screen or preview?

Did you build a new dev client for Expo?

What do you see in the logs?

**Comment by rmd1710714107** [comment]
i add it in a existing project and i build it as a apk file.   Then i install the file in my cell phone, but i didn't see anything in Home screen when i pick it to my Home screen.   Unfortunately, I don't see any logs.

> Where didn't the widget show anything? Home screen or preview?
> 
> Did you build a new dev client for Expo?
> 
> What do you see in the logs?

i add it in a existing project and i build it as a apk file.   Then i install the file in my cell phone, but i didn't see anything in Home screen when i pick it to my Home screen.   Unfortunately, I don't see any logs.

**Comment by sAleksovski** [comment]
Did you register a task handler (https://saleksovski.github.io/react-native-android-widget/docs/tutorial/register-task-handler)?

Can you try the same with a dev client in dev mode, so you can see the logs?

**Comment by rmd1710714107** [comment]
> Did you register a task handler (https://saleksovski.github.io/react-native-android-widget/docs/tutorial/register-task-handler)?
> 
> Can you try the same with a dev client in dev mode, so you can see the logs?

thank u，i forget to register a task handler. Now i can seet it in Home screen
