### ISSUE TITLE
react native 0.69 support?(Unable to determine the current character, it is not a string, number, array, or object)

### ISSUE THREAD

**Issue by chenkuangkuang** [sAleksovski/react-native-android-widget#42]
We are using react native 0.69, and after installed this package, the app cannot run.

The error is "Unable to determine the current character, it is not a string, number, array, or object", which is a issue in [react-native-community](https://github.com/react-native-community/cli/issues/1981).I donnot konw which package caused this error, but it can work after I uninstalled your package.

So I think may this package donot support react native 0.69, any suggestions?

**Comment by sAleksovski** [comment]
I just released `0.8.2`, can you try again?

**Comment by sAleksovski** [comment]
Looks like the build supports 0.69, but not the code in `RNWidgetConfigurationActivity`.

I'm not sure how I can update it so it can works with 0.69, while continuing to work with the newer versions.

I would suggest to either:
- Use `0.6.2` if you don't need the configuration activity
- Upgrade to newer React Native version
- Use [`patch-package`](https://www.npmjs.com/package/patch-package) to patch the code in `RNWidgetConfigurationActivity` with React Native 0.69 compatible code
