### ISSUE TITLE
issue with automatic linking: the package react-native-android-widget doesn't seemed to be linked

### ISSUE THREAD

**Issue by ZaidAli3642** [sAleksovski/react-native-android-widget#46]
Hi @sAleksovski! I am trying to use the library for my project and it seems that there is a linking problem. I also have tried rebuilt the app but it doesn't seems to be working. Can you please tell me How can I link it manually if automatic doesn't work?

<img width="386" alt="Screenshot 2023-11-14 at 5 03 11 PM" src="https://github.com/sAleksovski/react-native-android-widget/assets/58937817/489921d5-5e14-4f44-adc6-8cba6625e43b">

"react-native": "0.62.2", is being used

**Comment by sAleksovski** [comment]
Hi @ZaidAli3642 .

It should link automatically when you install it. You need to rebuild the app so that the new native code is picked up, or build a new dev client if using Expo.

**Comment by ZaidAli3642** [comment]
> Hi @ZaidAli3642 .
> 
> It should link automatically when you install it. You need to rebuild the app so that the new native code is picked up, or build a new dev client if using Expo.
> 
> Edit: I just saw that you are using React Native 0.62.2.
> This is a very old version and is not supported.

Any way to link manually? May be that's the version issue of React native.

**Comment by sAleksovski** [comment]
In #42 we saw that 0.69 is not supported in the latest version.

I'm not exactly sure how to link it manually, since automatic linking always worked. You can check react native docs for manual linking for your version.

Even if you manage to link it, there might be other issues due to the old React Native version.

**Comment by sAleksovski** [comment]
I'll close this, since you are using very old react native version, and I'm pretty sure other stuff will not work too even if it is linked.

Please reopen this if you see the same problem on a newer react native version.
