### ISSUE TITLE
Super cool!

### ISSUE THREAD

**Issue by Noitidart** [sAleksovski/react-native-android-widget#5]
Just wanted to share that this is super cool. I've been using Expo and wanting to do an Android (and iOS but Ill try later) widget for a long time, but it was always to hairy and busy to figure out a clean way. Will definitely be using this soon thanks!

Just a side question: Do you know of any lib out there for iOS by chance?

I would love to donate to this package, do you have plans to open sponsorship? Just wanted to say thanks!

**Comment by sAleksovski** [comment]
Thanks!
Let me know if you build something, I would love to see it.

I don't know of any similar lib for iOS.

No plans for sponsorship right now, since GitHub sponsors is not available in my country.

**Comment by Noitidart** [comment]
Ah thank you. That's silly of Github. Hopefully soon they open up one, I'll also be on the lookout.

**Comment by Milk-Cool** [comment]
By the way, quick question: will it say anything if I use it with Expo Go on iOS?

**Comment by Milk-Cool** [comment]
By the way, quick question: will it say anything if I use it with Expo Go on iOS?

**Comment by sAleksovski** [comment]
What do you mean by "say anything"?

It won't work on iOS, but should not throw errors.

**Comment by Milk-Cool** [comment]
> It won't work on iOS, but should not throw errors.

Yeah, i was wondering if it would give me an error on iOS. Thanks for the reply!
