### ISSUE TITLE
Handling click on second-level children of ListWidget

### ISSUE THREAD

**Issue by robinmitra** [sAleksovski/react-native-android-widget#53]
Hello, thanks for your work on this library 🙌🏼 

I'm aware that only the first-level children of ListWidget can be clicked as per:

> Only the first-level children of the ListWidget can be ["clicked"](https://saleksovski.github.io/react-native-android-widget/docs/handling-clicks). We can still set clickAction on the sub-widgets, but they will not respond to clicks.

However, I thought I'd still ask in case you have any suggestions for implementing my use-case:

I have a list of tasks in a widget, and each task has a checkbox before it. When a user taps on the checkbox, the task should be completed. If they tap on the title of the task, the task should be opened in the app. 

Is this pattern possible using this library? I saw the ListWidget example which appears to have an archive button next to each item, but it doesn't do anything.

**Comment by sAleksovski** [comment]
Hi,

That pattern is currently not possible using this library.
I might try to implement it when I have some free time.

The example list widget has an archive icon, but it does not do anything, just replicates the Gmail widget look.

**Comment by sAleksovski** [comment]
I just released `0.11.1` that allows handling click on second-level children in ListWidget.

You can check the updated ListWidget example.

**Comment by robinmitra** [comment]
That's amazing! I'll try it out tonight. Thank you so much 😃
