### ISSUE TITLE
List re-render after send the app to background

### ISSUE THREAD

**Issue by Facundo1609** [sAleksovski/react-native-android-widget#54]
Hey! How are you?
I'm testing the Debug Events widget and I realized that the List component "renders" again every time I send the app to background. In this case, the list scrolls up and shows the first item again
Is it possible to keep the position of the list even if I open or close the app? 

https://github.com/sAleksovski/react-native-android-widget/assets/84348170/3b8b3aaf-e3ab-47e9-990b-16d0aa7a476b

Other widgets that use the List component have the same problem. Also, there is a "little jump" on some texts after closing or sending the app to background

https://github.com/sAleksovski/react-native-android-widget/assets/84348170/bfbc2562-00a5-45c9-a75b-5750a3caf64c

**Comment by sAleksovski** [comment]
Dev mode on emulator or production build on device?

I just tried it using the example app apk using the list widget demo, and it works correctly (does not scroll when I send the app to background, nor the text jumps).

**Comment by Facundo1609** [comment]
Hey! It works if I use a production build on a real device. Thanks!
