### ISSUE TITLE
Questions about CodePush

### ISSUE THREAD

**Issue by baesumin** [sAleksovski/react-native-android-widget#55]
hello. I use an Android widget, and it may be that I set it up wrong, but the widget came out fine before applying Code Push, but when I install the Android widget after Code Push is applied, a blank screen appears. Could it have something to do with applying code push?

**Comment by sAleksovski** [comment]
I can't really say without seeing some logs.

But whenever you update a library that has native code changes, you must rebuild the apk and cannot use code push, since code push only updates the JavaScript.
