### ISSUE TITLE
Amazing lib! How about scrolling?

### ISSUE THREAD

**Issue by mark-yacoub** [sAleksovski/react-native-android-widget#6]
Hey, I was dreading creating a widget for android but i came across this (first result on google!).
So far things are so great! I have a question though:

Is there a way to make the view scrollable? I tried adding `overflow: 'auto',` to `FlexWidget` style but that didn't work

**Comment by sAleksovski** [comment]
Thanks!

No, this library does not support scrollable widgets.
They are a bit more complex to implement using ["collection widgets"](https://developer.android.com/develop/ui/views/appwidgets/collections).

I'm not sure if it is even possible to implement them using React Native, but I might try when I have more free time.

**Comment by sAleksovski** [comment]
Hi,

I just released `0.5.0` version of the library which includes a `ListWidget`.

You can see the docs about how to use it in the [ListWidget documentation](https://saleksovski.github.io/react-native-android-widget/docs/primitives/list-widget).

Also, you can see it in action in the `example-app` included in the [release](https://github.com/sAleksovski/react-native-android-widget/releases/tag/v0.5.0).
