### ISSUE TITLE
Question: How to force re-update/reload widget?

### ISSUE THREAD

**Issue by longb1997** [sAleksovski/react-native-android-widget#62]
Hello, first of all thank you for a great library.

In my case I needed to force a reload/re-update of data in the widget. For example, when a user logs out, they log in to another account, the widget will be reloaded. Is there any method to help me call in Logout/Login function?

**Comment by sAleksovski** [comment]
You can call `requestWidgetUpdate` at any time.

See https://saleksovski.github.io/react-native-android-widget/docs/update-widget#requestwidgetupdate
