### ISSUE TITLE
Using clickAction for second-level children in ListWidget break layout

### ISSUE THREAD

**Issue by longb1997** [sAleksovski/react-native-android-widget#63]
Hello, first of all, thank you for a great library.

In my case, I got this error when using clickAction, this error only occurred when I changed the position of the widget, then I scrolled the list. It will automatically buffer the top of the list, if you do not change the widget position after initiating it will not cause an error.

I have added a video here:

https://github.com/sAleksovski/react-native-android-widget/assets/48817520/e0ecaad4-0a71-4dab-b68a-d30c17100edf

This is my code:
Edited: Check the comment for reproduce project

**Comment by sAleksovski** [comment]
Hi,

Can you share the complete code for the widget, along with the helper functions, that I can use to reproduce the error?
Or at least a simpler example?
I see `STextWidget` component, `daysOfWeek`, `daysMatrix`, `ColorWidget`... that are not defined, and I don't know what they should be.

**Comment by longb1997** [comment]
> Hi,
> 
> Can you share the complete code for the widget, along with the helper functions, that I can use to reproduce the error? Or at least a simpler example? I see `STextWidget` component, `daysOfWeek`, `daysMatrix`, `ColorWidget`... that are not defined, and I don't know what they should be.

Thanks for your reply, I've just updated the code to the question

**Comment by longb1997** [comment]
> Code is still not complete.
> 
> This section is not connected with anything:
> 
> ```
>   return (
>     <FlexWidget
>       style={{
>         width: 'match_parent',
>         alignItems: 'center',
>         justifyContent: 'center',
>       }}
>     >
>       <STextWidget text={`Something wrong: ${error}`} textStyle={{fontSize: 18, color: '#FFF'}} />
>     </FlexWidget>
>   );
> }
> ```
> 
> There are SVG files that are not present.
> 
> What is the input to this component? What is `data`?
> 
> Can you create a small project with only this widget that I can use to reproduce it?
> 
> Or fork this repo and recreate the widget in the example app.

Hi, Sorry for providing a lack of information. I just created a mini-project to reproduce it.
https://github.com/longb1997/widget-example

**Comment by sAleksovski** [comment]
I just released [`0.11.2`](https://github.com/sAleksovski/react-native-android-widget/releases/tag/v0.11.2) that should fix this issue.

Please try it and check if you can still reproduce the issue.

I'll close the issue, feel free to reopen it if you still have the problem.
