### ISSUE TITLE
Can't find the widget

### ISSUE THREAD

**Issue by kimgh06** [sAleksovski/react-native-android-widget#69]
I followed the tutorial, the build was succeeded.
But There's a problem.
I could not find the widget of the application.
I share you the screenshot.

I will wait for your answer.
![Screenshot_20240305-234504_One UI Home](https://github.com/sAleksovski/react-native-android-widget/assets/101877146/63ffbfd7-cec9-4f41-8d48-ac263e2981dc)

**Comment by sAleksovski** [comment]
You first need to use a [config plugin to register the widget](https://saleksovski.github.io/react-native-android-widget/docs/tutorial/register-widget-expo#use-config-plugin-in-appjsonconfigjsconfigts), then you need to [build a dev client](https://saleksovski.github.io/react-native-android-widget/docs/tutorial/register-widget-expo#build-dev-client).

Looks like in your project you have both `app.json` and `app.config.js`.
Use only one of them, and delete the other one.
