### ISSUE TITLE
How to get items from disk

### ISSUE THREAD

**Issue by mark-yacoub** [sAleksovski/react-native-android-widget#7]
Hey - first of all thank you for doing this it's so nice!

I have a question about fetching data. I see in the demos that the data you're displaying are static inside the view, but what if i wanna grab data from the server or even from localstorage. if i can't use hooks then i can't use await functions. Am i missing something? to fetch items from local storage.

Thanks!

**Comment by sAleksovski** [comment]
You can use async functions when working with the widgets.

- [registerTaskHandler](https://saleksovski.github.io/react-native-android-widget/docs/api/register-widget-task-handler) is an async function in which you can use `await` to resolve a promise, and then render the widget with the required data.
- [requestWidgetUpdate](https://saleksovski.github.io/react-native-android-widget/docs/public-api/#requestwidgetupdate) also accepts an async function for `renderWidget`, where you can do async actions (network call, read from AsyncStorage...)

Here is an example from the example app where AsyncStorage is used to read data before rendering the widget: https://github.com/sAleksovski/react-native-android-widget/blob/master/example/src/widgetTaskHandler.tsx#L38-L41

Ideally you would not do the fetching from the widgets, and the would be "dumb", they would only know how to render the data they receive, and you should do the data fetching outside the widget.
