### ISSUE TITLE
Open <ConfigurableWidget/> with clickAction inside any <widget/>

### ISSUE THREAD

**Issue by abdul-wajid-afridi** [sAleksovski/react-native-android-widget#71]
i don't know how to show the pop up <ConfigurableWidget/> with click on the widget as you have done with counter but i want to show that same setCount numbers with action click on the widget and show the pop up with clickAction=""

**Comment by abdul-wajid-afridi** [comment]
@sAleksovski how can i show that <ConfigurableWidget/> with clickAction on the homescreen widget     `<FlexWidget
            style={{
              flexDirection: "row",
              flexGap: 4,
            }}
            clickAction="RENDER_WIDGET"
          >show pop up </FlexWidget> `

**Comment by sAleksovski** [comment]
You need to long-press the widget for the option to reconfigure it to be shown. This is an Android thing, and is not controlled by this library.

If you want to open it with a button in your widget, you will need to use a deep link in your app where you will render the same (or similar) component as in the configuration screen.

```
clickAction="OPEN_URI"
clickActionData={{
  uri: 'androidwidgetexample://deep-link-for-config-activity/' + widgetId,
}}
```

**Comment by abdul-wajid-afridi** [comment]
yes i pressed the long button but it does not show configuration at the
start when dragging widget it show but when hold widget it does not show
any configuration about widget

**Comment by sAleksovski** [comment]
![Screenshot_20240310_081951_Nova Launcher.jpg](https://github.com/sAleksovski/react-native-android-widget/assets/7473800/39696a80-c7b2-4004-927e-1307342195e7)

You have to press the widget settings. This is on Nova launcher.
Your launcher might be different.

If you want a custom button on the widget, see my previous comment about how to implement it.

**Comment by abdul-wajid-afridi** [comment]
does other launcher supports this?
because everyone might not have nova launcher

**Comment by sAleksovski** [comment]
Nova was just an example, other launchers support this too

**Comment by abdul-wajid-afridi** [comment]
but i tried your example too and also i created my own configurable widgets
but it does not show settings is it need any other configuration too
because i am stuck from past 10 days and this does not show settings i
tried everything. even i copy past your example for testing that even
doesn't work

**Comment by sAleksovski** [comment]
What do you see when you long press the widget?
Please share a screenshot

**Comment by abdul-wajid-afridi** [comment]
i see 'Remove' and 'App info' only

**Comment by sAleksovski** [comment]
If it opens when you drop the widget, then your launcher does not support reconfiguration of the widget.

> If you want to open it with a button in your widget, you will need to use a deep link in your app where you will render the same (or similar) component as in the configuration screen.
> 
> ```
> clickAction="OPEN_URI"
> clickActionData={{
>   uri: 'androidwidgetexample://deep-link-for-config-activity/' + widgetId,
> }}
> ```

**Comment by abdul-wajid-afridi** [comment]
so this mean i will use the deep linking

**Comment by abdul-wajid-afridi** [comment]
how can we pass dynamic colors to svgwidgets?

**Comment by sAleksovski** [comment]
> how can we pass dynamic colors to svgwidgets?

This is unrelated to this issue.
You can use string svg, and use string interpolation/concatenation to change the colors.

I'll close this issue since I explained how you can use deep-linking to open a screen.
