### ISSUE TITLE
open a specific screen `clickAction` and `clickActionData` with expo router does not change screen with new click action

### ISSUE THREAD

**Issue by abdul-wajid-afridi** [sAleksovski/react-native-android-widget#72]
when click on widget it opens app specific screen which i want but when i minimize app and click on widget with different screen it does go to specific screen and opens old screen but when clear every thing and kill app then it opens specific screen for first time
`clickAction="OPEN_URI"
  clickActionData={{ uri: "learn-expo-router://contact" }}`

**Comment by abdul-wajid-afridi** [comment]
deep linking is working but it does not change the old screen with new one if app is open 
e.g lets say i have clicked on widget for about screen and again i clicked on contact screen so it will not be updated with old one
i tried it with react navigation its fine but with expo router it not changing or updating the screen if app is open in background

**Comment by sAleksovski** [comment]
I'll close this since it is fine with React Navigation. 

It is probably a bug in expo-router. See if there is a newer version, it a known issue there.
