### ISSUE TITLE
Image Styling

### ISSUE THREAD

**Issue by iMJumpmxn** [sAleksovski/react-native-android-widget#75]
Hi Stefan,

thank you for building this Library!

Is there any way support for setting the position to absolute for images?

**Comment by abdul-wajid-afridi** [comment]
https://saleksovski.github.io/react-native-android-widget/docs/primitives/overlap-widget
@iMJumpmxn  try this

**Comment by iMJumpmxn** [comment]
Worked thank you!
Any idea how to use the image styles "resizeMode" here?

**Comment by abdul-wajid-afridi** [comment]
i don't know about that but `height: 'match_parent', width: 'match_parent'` might help you
what's your target?

**Comment by sAleksovski** [comment]
Closing this since the original question is answered by @abdul-wajid-afridi .

`resizeMode` is not currently not supported. Please open another issue if you need it.
