### ISSUE TITLE
Update widget by widgetId

### ISSUE THREAD

**Issue by ReddyyZ** [sAleksovski/react-native-android-widget#77]
When I use requestWidgetUpdate, it updates all the widgets that have the same name, but I want to update a specific widget.
I did not found anything like that in the documentation.
Is that possible?

**Comment by sAleksovski** [comment]
Currently it is not possible.

The initial idea was that you don't need to keep track if widgets are added on the home screen and always call `requestWidgetUpdate` when you want to update the widget (if one is present).
This way you don't need to store the `widgetId`, and request updates for that specific widget.

But I can add it if you need it.

**Comment by ReddyyZ** [comment]
If you could add this, it would be amazing! It will help me a lot

**Comment by sAleksovski** [comment]
I just published [`0.13.0`](https://github.com/sAleksovski/react-native-android-widget/releases/tag/v0.13.0) that has [`requestWidgetUpdateById`](https://saleksovski.github.io/react-native-android-widget/docs/api/request-widget-update-by-id) function.

**Comment by ReddyyZ** [comment]
Thanks!!
