### ISSUE TITLE
bug: ListWidget scrolling issue

### ISSUE THREAD

**Issue by mritul** [sAleksovski/react-native-android-widget#78]
I've used the example [ListWidgetDemo](https://github.com/sAleksovski/react-native-android-widget/blob/master/example/src/widgets/ListDemoWidget.tsx) code in this same repository:

Issue: The preview scrolling works just fine but when I actually add the widget to the home screen the scrolling gets nested with the swipe-up -to-open the menu and the ListWidget fails to scroll

Demo:
https://github.com/sAleksovski/react-native-android-widget/assets/84136875/504e3a14-49b3-40f9-b17b-8131a16c9a78

Hope there is a fix to this solution and any sort of help would be appreciated.

**Comment by sAleksovski** [comment]
I cannot reproduce this. Looks related to #49 

What device/launcher are you using?
Can you try using any other widget that has scrollable list, for example the Gmail widget?
Also please try with example-app.apk file from the latest release (https://github.com/sAleksovski/react-native-android-widget/releases/tag/v0.13.0)
Can you also try to fix the icon, I see that on both issues the icons are broken.

**Comment by sAleksovski** [comment]
Unfortunately this looks like an OnePlus bug, or at least OnePlus Launcher bug.

Check https://www.google.com/search?q=oneplus+widget+not+scrolling

Can you try another launcher to confirm it is the launcher and not the OS?
