### ISSUE TITLE
Question: ListWidget can be horizontally scrollable?

### ISSUE THREAD

**Issue by longb1997** [sAleksovski/react-native-android-widget#82]
Hi, I checked the documentation and didn't see any guidance on direction, will it be supported in the future?

**Comment by sAleksovski** [comment]
Current `ListWidget` is implemented using `ListView`, which does not support horizontal scroll. 

See https://developer.android.com/develop/ui/views/appwidgets/collections

I don't have plans to implement horizontal scroll in the near future, since it would have to use a different primitive.
