### ISSUE TITLE
Re-render widget from WebSocket message

### ISSUE THREAD

**Issue by juliengbt** [sAleksovski/react-native-android-widget#88]
Hey!

First of all I want to that the library is very cool, easy to set up and use. I have a question though, would it be possible to open a WebSocket connection while the app is closed, and update the widget when a message is received from that websocket connection ?

EDIT: After some research, it seems having a websocket connection opened while the app is closed isn't possible. I will have to use push notifications, listen to new notification and then update the widget from there. Would that be possible ?

**Comment by sAleksovski** [comment]
Sure, it's possible if the push notification is handled in javascript.

Push notifications are not something that is handled in this library directly, you will have to use something else, and call `requestWidgetUpdate` in the push notification handler.

See https://saleksovski.github.io/react-native-android-widget/docs/update-widget#requestwidgetupdate
