### ISSUE TITLE
Text styling

### ISSUE THREAD

**Issue by juliengbt** [sAleksovski/react-native-android-widget#89]
Hey!

Is there a way to style some specific word in a TextWidget. In react native you would do something like :

```jsx
<Text>
  This is <Text style={{color: 'red'}}>red</Text> and this is <Text style={{color: 'blue'}}>blue</Text>.
</Text>
```

But TextWidget doesn't take any children and having multiple TextWidget in a FlexWidget (row) would not fit it the is too long.

**Comment by sAleksovski** [comment]
Hi. 

This is currently not supported, and I'm not sure that it can be implemented easily. 

You can try using the `SvgWidget` and the `<text>` element. See the examples in https://www.w3schools.com/graphics/svg_text.asp

**Comment by juliengbt** [comment]
Alright thanks, I'll give it a try
