### ISSUE TITLE
Updated widget after click button

### ISSUE THREAD

**Issue by pixelkoduje** [sAleksovski/react-native-android-widget#92]
How to create a circle button that refreshes the widget content when clicked?  without opening the application.

**Comment by sAleksovski** [comment]
https://saleksovski.github.io/react-native-android-widget/docs/handling-clicks

**Comment by pixelkoduje** [comment]
Do you plan to implement this library for IOS and Expo dev?

**Comment by sAleksovski** [comment]
No plans to support iOS for now. 

Expo is supported, see the docs https://saleksovski.github.io/react-native-android-widget/docs
