### ISSUE TITLE
Will this library be made for IOS in the future?

### ISSUE THREAD

**Issue by UmarbekSaidov** [sAleksovski/react-native-android-widget#93]
The library is great. But at the moment we can only use it for Android. It would be great if we could use it for iOS

**Comment by sAleksovski** [comment]
Hi. 

I considered it, but don't have plans to build it. I think it would take up too much of my time.

I've seen https://github.com/bndkt/react-native-widget-extension for iOS widgets, but I haven't tried it. Maybe it will be of some use to you.

Thanks for the kind words about my library.
