### ISSUE TITLE
Can't get widget components to render with Expo

### ISSUE THREAD

**Issue by JustinMarinelli** [sAleksovski/react-native-android-widget#98]
I followed the steps to start a React Native app using Expo here: https://docs.expo.dev/get-started/next-steps/
I am successfully able to start a dev server and alter what's shown on the screen, in a simple Hello World app. Here is my `index.tsx` file:
```
import { Text, View } from "react-native";

export default function Index() {
  return (
    <View
      style={{
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
      }}
    >
      <Text>Welcome!</Text>
    </View>
  );
}

```

I then installed React Native Android Widget and started going through the tutorial. After adding `HelloWidget.tsx` shown in the tutorial to my project, I change my `Index()` function to:
```
import { HelloWidget } from "@/x/HelloWidget";

export default function Index() {
  return HelloWidget();
}
```
Now, nothing is rendered. Am I missing something? Shouldn't I see "Hello" rendered on the screen?

**Comment by sAleksovski** [comment]
Please finish the tutorial

https://saleksovski.github.io/react-native-android-widget/docs/tutorial/widget-preview
